create table Residents (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	country VARCHAR(50)
);
insert into Residents (id, first_name, last_name, email, gender, country) values (1, 'Layne', 'Langthorn', 'llangthorn0@businessweek.com', 'Female', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (2, 'Foss', 'People', 'fpeople1@nhs.uk', 'Male', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (3, 'Maria', 'Venables', 'mvenables2@earthlink.net', 'Female', 'Russia');
insert into Residents (id, first_name, last_name, email, gender, country) values (4, 'Damon', 'Josland', 'djosland3@shinystat.com', 'Male', 'Czech Republic');
insert into Residents (id, first_name, last_name, email, gender, country) values (5, 'Jelene', 'Seabert', 'jseabert4@fema.gov', 'Female', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (6, 'Lorens', 'Allcott', null, 'Male', 'Egypt');
insert into Residents (id, first_name, last_name, email, gender, country) values (7, 'Jarret', 'Sidey', 'jsidey6@europa.eu', 'Male', 'Philippines');
insert into Residents (id, first_name, last_name, email, gender, country) values (8, 'Binny', 'Watkiss', 'bwatkiss7@cdbaby.com', 'Female', 'Portugal');
insert into Residents (id, first_name, last_name, email, gender, country) values (9, 'Dore', 'Camble', 'dcamble8@vk.com', 'Male', 'Colombia');
insert into Residents (id, first_name, last_name, email, gender, country) values (10, 'Malcolm', 'Winchester', null, 'Male', 'Indonesia');
insert into Residents (id, first_name, last_name, email, gender, country) values (11, 'Donica', 'des Remedios', 'ddesremediosa@ebay.co.uk', 'Female', 'Netherlands');
insert into Residents (id, first_name, last_name, email, gender, country) values (12, 'Tab', 'Muddicliffe', 'tmuddicliffeb@mac.com', 'Male', 'Greece');
insert into Residents (id, first_name, last_name, email, gender, country) values (13, 'Aldridge', 'Threadgill', 'athreadgillc@deliciousdays.com', 'Genderfluid', 'Myanmar');
insert into Residents (id, first_name, last_name, email, gender, country) values (14, 'Damita', 'Dinning', null, 'Polygender', 'Portugal');
insert into Residents (id, first_name, last_name, email, gender, country) values (15, 'Martyn', 'Grahamslaw', 'mgrahamslawe@newsvine.com', 'Male', 'Netherlands');
insert into Residents (id, first_name, last_name, email, gender, country) values (16, 'Corri', 'Cheeseman', 'ccheesemanf@twitpic.com', 'Female', 'Japan');
insert into Residents (id, first_name, last_name, email, gender, country) values (17, 'Clair', 'Jolliss', null, 'Female', 'France');
insert into Residents (id, first_name, last_name, email, gender, country) values (18, 'Markus', 'Hambleton', 'mhambletonh@godaddy.com', 'Male', 'Poland');
insert into Residents (id, first_name, last_name, email, gender, country) values (19, 'Priscella', 'Temporal', 'ptemporali@delicious.com', 'Female', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (20, 'Genna', 'Taylor', null, 'Female', 'Portugal');
insert into Residents (id, first_name, last_name, email, gender, country) values (21, 'Regine', 'Kenwin', 'rkenwink@usda.gov', 'Female', 'Russia');
insert into Residents (id, first_name, last_name, email, gender, country) values (22, 'Garvey', 'Klezmski', 'gklezmskil@amazon.co.jp', 'Male', 'Philippines');
insert into Residents (id, first_name, last_name, email, gender, country) values (23, 'Leontine', 'Griggs', null, 'Female', 'Bolivia');
insert into Residents (id, first_name, last_name, email, gender, country) values (24, 'Ruby', 'Newtown', null, 'Male', 'Brazil');
insert into Residents (id, first_name, last_name, email, gender, country) values (25, 'Ashlen', 'Barraclough', null, 'Agender', 'Ukraine');
insert into Residents (id, first_name, last_name, email, gender, country) values (26, 'Laurie', 'Brown', 'lbrownp@hostgator.com', 'Female', 'Canada');
insert into Residents (id, first_name, last_name, email, gender, country) values (27, 'Grethel', 'Piscot', 'gpiscotq@google.it', 'Female', 'American Samoa');
insert into Residents (id, first_name, last_name, email, gender, country) values (28, 'Melisande', 'MacIlory', 'mmaciloryr@cdbaby.com', 'Female', 'Philippines');
insert into Residents (id, first_name, last_name, email, gender, country) values (29, 'Rosco', 'Upham', 'ruphams@umn.edu', 'Male', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (30, 'Ally', 'Olivia', null, 'Female', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (31, 'Barbey', 'Flack', 'bflacku@shutterfly.com', 'Female', 'Denmark');
insert into Residents (id, first_name, last_name, email, gender, country) values (32, 'Saidee', 'Happert', 'shappertv@walmart.com', 'Female', 'Brazil');
insert into Residents (id, first_name, last_name, email, gender, country) values (33, 'Tonnie', 'MacNockater', 'tmacnockaterw@earthlink.net', 'Male', 'Philippines');
insert into Residents (id, first_name, last_name, email, gender, country) values (34, 'Dottie', 'Filipyev', 'dfilipyevx@youtu.be', 'Female', 'United States');
insert into Residents (id, first_name, last_name, email, gender, country) values (35, 'Ebony', 'Domanek', null, 'Female', 'Vietnam');
insert into Residents (id, first_name, last_name, email, gender, country) values (36, 'Hakeem', 'Vedikhov', 'hvedikhovz@marriott.com', 'Male', 'Macedonia');
insert into Residents (id, first_name, last_name, email, gender, country) values (37, 'Maggi', 'Mansel', null, 'Female', 'Indonesia');
insert into Residents (id, first_name, last_name, email, gender, country) values (38, 'Yvor', 'Lethardy', null, 'Male', 'Philippines');
insert into Residents (id, first_name, last_name, email, gender, country) values (39, 'Clive', 'Garms', 'cgarms12@mashable.com', 'Male', 'United States');
insert into Residents (id, first_name, last_name, email, gender, country) values (40, 'Aguistin', 'Tixier', 'atixier13@xing.com', 'Male', 'Sweden');
insert into Residents (id, first_name, last_name, email, gender, country) values (41, 'Caleb', 'Van Oort', 'cvanoort14@freewebs.com', 'Male', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (42, 'Giffer', 'Wragge', 'gwragge15@aol.com', 'Male', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (43, 'Nerta', 'Oswal', null, 'Female', 'Somalia');
insert into Residents (id, first_name, last_name, email, gender, country) values (44, 'Dee', 'Ramsden', null, 'Female', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (45, 'Lanie', 'Battelle', 'lbattelle18@a8.net', 'Female', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (46, 'Teddie', 'Juppe', 'tjuppe19@google.it', 'Female', 'South Africa');
insert into Residents (id, first_name, last_name, email, gender, country) values (47, 'Tammara', 'Chadband', null, 'Female', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (48, 'Alfons', 'Lamzed', null, 'Male', 'Canada');
insert into Residents (id, first_name, last_name, email, gender, country) values (49, 'Bourke', 'Brotherheed', 'bbrotherheed1c@google.com.au', 'Male', 'Russia');
insert into Residents (id, first_name, last_name, email, gender, country) values (50, 'Armstrong', 'Ebenezer', null, 'Agender', 'Poland');
insert into Residents (id, first_name, last_name, email, gender, country) values (51, 'Rouvin', 'Averay', 'raveray1e@pcworld.com', 'Male', 'Nigeria');
insert into Residents (id, first_name, last_name, email, gender, country) values (52, 'Tommy', 'Babe', null, 'Male', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (53, 'Gabbi', 'Gagie', 'ggagie1g@people.com.cn', 'Genderqueer', 'Equatorial Guinea');
insert into Residents (id, first_name, last_name, email, gender, country) values (54, 'Demetra', 'Lindsay', 'dlindsay1h@jalbum.net', 'Female', 'Syria');
insert into Residents (id, first_name, last_name, email, gender, country) values (55, 'Drew', 'Symons', 'dsymons1i@stumbleupon.com', 'Male', 'Brazil');
insert into Residents (id, first_name, last_name, email, gender, country) values (56, 'Eustace', 'McJerrow', 'emcjerrow1j@theguardian.com', 'Male', 'Colombia');
insert into Residents (id, first_name, last_name, email, gender, country) values (57, 'Vic', 'Riche', null, 'Male', 'France');
insert into Residents (id, first_name, last_name, email, gender, country) values (58, 'Nealy', 'Sodeau', 'nsodeau1l@1688.com', 'Male', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (59, 'Anita', 'Hollier', 'ahollier1m@youtu.be', 'Female', 'Jordan');
insert into Residents (id, first_name, last_name, email, gender, country) values (60, 'Sherri', 'Deboo', 'sdeboo1n@ifeng.com', 'Female', 'Malaysia');
insert into Residents (id, first_name, last_name, email, gender, country) values (61, 'Shayne', 'Davidsen', null, 'Male', 'Yemen');
insert into Residents (id, first_name, last_name, email, gender, country) values (62, 'Ev', 'Lewing', 'elewing1p@sphinn.com', 'Male', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (63, 'Chip', 'Horsburgh', 'chorsburgh1q@amazon.com', 'Male', 'Russia');
insert into Residents (id, first_name, last_name, email, gender, country) values (64, 'Broddie', 'Josupeit', 'bjosupeit1r@mac.com', 'Male', 'Malaysia');
insert into Residents (id, first_name, last_name, email, gender, country) values (65, 'Samson', 'McElane', null, 'Male', 'Indonesia');
insert into Residents (id, first_name, last_name, email, gender, country) values (66, 'Chiquita', 'Dallimare', null, 'Female', 'Indonesia');
insert into Residents (id, first_name, last_name, email, gender, country) values (67, 'Hurley', 'Wagg', 'hwagg1u@purevolume.com', 'Male', 'Japan');
insert into Residents (id, first_name, last_name, email, gender, country) values (68, 'Zachariah', 'Fawcitt', 'zfawcitt1v@latimes.com', 'Male', 'Peru');
insert into Residents (id, first_name, last_name, email, gender, country) values (69, 'Bondy', 'Fairy', null, 'Male', 'Peru');
insert into Residents (id, first_name, last_name, email, gender, country) values (70, 'Bernete', 'Titta', 'btitta1x@answers.com', 'Female', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (71, 'Daren', 'Rampton', 'drampton1y@youtube.com', 'Male', 'Colombia');
insert into Residents (id, first_name, last_name, email, gender, country) values (72, 'Read', 'Mecchi', 'rmecchi1z@time.com', 'Male', 'Brazil');
insert into Residents (id, first_name, last_name, email, gender, country) values (73, 'Elsinore', 'Sainthill', 'esainthill20@reuters.com', 'Bigender', 'Czech Republic');
insert into Residents (id, first_name, last_name, email, gender, country) values (74, 'Constantine', 'Hawkswell', null, 'Bigender', 'Portugal');
insert into Residents (id, first_name, last_name, email, gender, country) values (75, 'Evangelia', 'Dainty', 'edainty22@weather.com', 'Female', 'Brazil');
insert into Residents (id, first_name, last_name, email, gender, country) values (76, 'Florri', 'Beavors', 'fbeavors23@feedburner.com', 'Female', 'Armenia');
insert into Residents (id, first_name, last_name, email, gender, country) values (77, 'Alvie', 'Degli Antoni', 'adegliantoni24@oakley.com', 'Male', 'Serbia');
insert into Residents (id, first_name, last_name, email, gender, country) values (78, 'Tobe', 'Semark', 'tsemark25@harvard.edu', 'Female', 'Sweden');
insert into Residents (id, first_name, last_name, email, gender, country) values (79, 'Dareen', 'McOnie', 'dmconie26@scientificamerican.com', 'Female', 'Indonesia');
insert into Residents (id, first_name, last_name, email, gender, country) values (80, 'Phelia', 'Gartshore', null, 'Female', 'Colombia');
insert into Residents (id, first_name, last_name, email, gender, country) values (81, 'Hugues', 'Edleston', 'hedleston28@howstuffworks.com', 'Male', 'Sweden');
insert into Residents (id, first_name, last_name, email, gender, country) values (82, 'Ev', 'Girod', null, 'Male', 'France');
insert into Residents (id, first_name, last_name, email, gender, country) values (83, 'Rusty', 'Loveland', 'rloveland2a@amazonaws.com', 'Male', 'Russia');
insert into Residents (id, first_name, last_name, email, gender, country) values (84, 'Hilary', 'Conn', 'hconn2b@prnewswire.com', 'Male', 'Poland');
insert into Residents (id, first_name, last_name, email, gender, country) values (85, 'Kermie', 'Sains', 'ksains2c@chronoengine.com', 'Male', 'Philippines');
insert into Residents (id, first_name, last_name, email, gender, country) values (86, 'Jermaine', 'Manclark', 'jmanclark2d@pbs.org', 'Female', 'Tajikistan');
insert into Residents (id, first_name, last_name, email, gender, country) values (87, 'Caprice', 'Devita', null, 'Female', 'Finland');
insert into Residents (id, first_name, last_name, email, gender, country) values (88, 'Gabie', 'Ephgrave', 'gephgrave2f@census.gov', 'Female', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (89, 'Farlie', 'Pindred', 'fpindred2g@earthlink.net', 'Male', 'Russia');
insert into Residents (id, first_name, last_name, email, gender, country) values (90, 'Anabella', 'Lewinton', 'alewinton2h@theguardian.com', 'Polygender', 'Russia');
insert into Residents (id, first_name, last_name, email, gender, country) values (91, 'Madella', 'Wheowall', 'mwheowall2i@merriam-webster.com', 'Female', 'Pakistan');
insert into Residents (id, first_name, last_name, email, gender, country) values (92, 'Gage', 'Sinkings', 'gsinkings2j@huffingtonpost.com', 'Male', 'Brazil');
insert into Residents (id, first_name, last_name, email, gender, country) values (93, 'Mollie', 'Valerius', null, 'Female', 'Chile');
insert into Residents (id, first_name, last_name, email, gender, country) values (94, 'Jessica', 'Winear', 'jwinear2l@plala.or.jp', 'Female', 'Dominican Republic');
insert into Residents (id, first_name, last_name, email, gender, country) values (95, 'Calv', 'Jendas', 'cjendas2m@usa.gov', 'Male', 'Pakistan');
insert into Residents (id, first_name, last_name, email, gender, country) values (96, 'Lucian', 'Adanez', 'ladanez2n@hatena.ne.jp', 'Male', 'Indonesia');
insert into Residents (id, first_name, last_name, email, gender, country) values (97, 'Gisela', 'Belverstone', 'gbelverstone2o@creativecommons.org', 'Female', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (98, 'Isaiah', 'Thompson', 'ithompson2p@dyndns.org', 'Male', 'China');
insert into Residents (id, first_name, last_name, email, gender, country) values (99, 'Alexandr', 'Guiso', 'aguiso2q@alexa.com', 'Male', 'Mexico');
insert into Residents (id, first_name, last_name, email, gender, country) values (100, 'Reena', 'Louw', 'rlouw2r@taobao.com', 'Female', 'Indonesia');