create table users (
	id INT,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	gender VARCHAR(50),
	dob DATE,
	country VARCHAR(50)
);
insert into users (id, first_name, last_name, email, gender, dob, country) values (1, 'Livvie', null, null, 'Female', '2000-09-23', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (2, 'Harlie', null, 'hcrewther1@gravatar.com', 'Female', '2008-08-12', 'Lebanon');
insert into users (id, first_name, last_name, email, gender, dob, country) values (3, 'Ofelia', 'Wolpert', 'owolpert2@prnewswire.com', 'Female', '2011-05-19', 'Netherlands');
insert into users (id, first_name, last_name, email, gender, dob, country) values (4, 'Miran', 'Comi', 'mcomi3@reddit.com', 'Female', '1993-11-02', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (5, 'Darleen', null, null, 'Female', '2018-01-31', 'Dominican Republic');
insert into users (id, first_name, last_name, email, gender, dob, country) values (6, 'Tommie', 'McMychem', null, 'Female', '2022-03-03', 'Nigeria');
insert into users (id, first_name, last_name, email, gender, dob, country) values (7, 'Sarene', null, null, 'Female', '2000-08-04', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (8, 'Opal', null, 'orymmer7@prlog.org', 'Female', '2024-01-27', 'United States');
insert into users (id, first_name, last_name, email, gender, dob, country) values (9, 'Nefen', 'Goodman', 'ngoodman8@topsy.com', 'Male', '2011-10-01', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (10, 'Suki', 'Duigan', 'sduigan9@webnode.com', 'Female', '1998-01-19', 'France');
insert into users (id, first_name, last_name, email, gender, dob, country) values (11, 'Currey', 'Knocker', null, 'Male', '2009-09-23', 'Ukraine');
insert into users (id, first_name, last_name, email, gender, dob, country) values (12, 'Anabel', 'Raven', 'aravenb@yellowpages.com', 'Female', '2014-11-18', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (13, 'Zackariah', 'Pandya', 'zpandyac@imdb.com', 'Male', '2008-06-14', 'Bosnia and Herzegovina');
insert into users (id, first_name, last_name, email, gender, dob, country) values (14, 'William', null, null, 'Male', '2016-08-06', 'Japan');
insert into users (id, first_name, last_name, email, gender, dob, country) values (15, 'Tracee', 'Mongain', 'tmongaine@seattletimes.com', 'Female', '1999-12-24', 'Thailand');
insert into users (id, first_name, last_name, email, gender, dob, country) values (16, 'Tyler', 'Rostron', 'trostronf@wired.com', 'Male', '2014-06-14', 'Poland');
insert into users (id, first_name, last_name, email, gender, dob, country) values (17, 'Jacqueline', null, null, 'Polygender', '1996-06-14', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (18, 'Mahmud', null, 'mbuxtonh@oracle.com', 'Male', '2020-01-29', 'Peru');
insert into users (id, first_name, last_name, email, gender, dob, country) values (19, 'Birch', 'Ainsley', 'bainsleyi@cbc.ca', 'Male', '1994-03-08', 'Curacao');
insert into users (id, first_name, last_name, email, gender, dob, country) values (20, 'Gleda', null, 'gbachelarj@wired.com', 'Female', '2017-06-18', 'Honduras');
insert into users (id, first_name, last_name, email, gender, dob, country) values (21, 'Ninon', null, 'npounderk@vkontakte.ru', 'Female', '1990-08-17', 'Belarus');
insert into users (id, first_name, last_name, email, gender, dob, country) values (22, 'Pieter', 'Rucklesse', 'prucklessel@google.pl', 'Male', '2004-04-27', 'Peru');
insert into users (id, first_name, last_name, email, gender, dob, country) values (23, 'Giselbert', null, 'gskitterelm@chron.com', 'Male', '2015-07-03', 'Ethiopia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (24, 'Gherardo', 'Rothchild', 'grothchildn@spiegel.de', 'Male', '2001-04-15', 'Madagascar');
insert into users (id, first_name, last_name, email, gender, dob, country) values (25, 'Brander', 'Dudlestone', 'bdudlestoneo@1688.com', 'Male', '2026-01-15', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (26, 'Gray', 'Garry', 'ggarryp@microsoft.com', 'Agender', '2017-04-26', 'Japan');
insert into users (id, first_name, last_name, email, gender, dob, country) values (27, 'Lanny', 'Morey', 'lmoreyq@nifty.com', 'Male', '2021-06-27', 'Brazil');
insert into users (id, first_name, last_name, email, gender, dob, country) values (28, 'Fairleigh', 'Bloxland', null, 'Male', '1993-03-21', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (29, 'Paige', 'Cumbridge', 'pcumbridges@youtube.com', 'Female', '2013-10-08', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (30, 'Jasmine', 'Kingscote', 'jkingscotet@imdb.com', 'Female', '2012-08-18', 'Brazil');
insert into users (id, first_name, last_name, email, gender, dob, country) values (31, 'Julian', 'McGuane', 'jmcguaneu@ycombinator.com', 'Male', '2000-07-21', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (32, 'Avery', 'Lauderdale', 'alauderdalev@bizjournals.com', 'Male', '1996-11-03', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (33, 'Karney', 'Strutton', 'kstruttonw@yahoo.com', 'Male', '2004-04-15', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (34, 'Gretta', 'MacConnechie', 'gmacconnechiex@webs.com', 'Female', '2013-03-29', 'Egypt');
insert into users (id, first_name, last_name, email, gender, dob, country) values (35, 'Jeffie', 'Alu', 'jaluy@ehow.com', 'Male', '1994-10-03', 'Netherlands');
insert into users (id, first_name, last_name, email, gender, dob, country) values (36, 'Mikel', 'Sheara', null, 'Male', '1996-09-23', 'Sweden');
insert into users (id, first_name, last_name, email, gender, dob, country) values (37, 'Barbabra', 'Leagas', 'bleagas10@lycos.com', 'Female', '2000-10-15', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (38, 'Edeline', 'Cottage', null, 'Female', '1995-12-06', 'Peru');
insert into users (id, first_name, last_name, email, gender, dob, country) values (39, 'Aura', 'Szymanski', 'aszymanski12@blogger.com', 'Female', '2019-05-04', 'Lithuania');
insert into users (id, first_name, last_name, email, gender, dob, country) values (40, 'Vittorio', 'Garrold', 'vgarrold13@theatlantic.com', 'Male', '2021-05-16', 'Vietnam');
insert into users (id, first_name, last_name, email, gender, dob, country) values (41, 'Sam', 'Gonnet', 'sgonnet14@people.com.cn', 'Female', '2009-07-18', 'France');
insert into users (id, first_name, last_name, email, gender, dob, country) values (42, 'Lillis', 'Salzburger', 'lsalzburger15@g.co', 'Female', '2006-01-27', 'Colombia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (43, 'Brnaba', 'Izakovitz', null, 'Male', '1995-04-27', 'Uganda');
insert into users (id, first_name, last_name, email, gender, dob, country) values (44, 'Flo', 'Vaughan', 'fvaughan17@alibaba.com', 'Female', '2005-02-07', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (45, 'Abby', 'Mayhead', 'amayhead18@apple.com', 'Male', '1994-10-26', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (46, 'Rey', 'Barthelmes', 'rbarthelmes19@alibaba.com', 'Male', '2000-03-18', 'Canada');
insert into users (id, first_name, last_name, email, gender, dob, country) values (47, 'Thomasin', null, 'tbraben1a@yolasite.com', 'Female', '2008-08-20', 'Japan');
insert into users (id, first_name, last_name, email, gender, dob, country) values (48, 'Bernadine', 'Staley', null, 'Female', '2016-06-22', 'Poland');
insert into users (id, first_name, last_name, email, gender, dob, country) values (49, 'Fern', 'Walster', null, 'Female', '2005-11-10', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (50, 'Anabel', 'Rowler', 'arowler1d@creativecommons.org', 'Female', '2010-08-12', 'Argentina');
insert into users (id, first_name, last_name, email, gender, dob, country) values (51, 'Marigold', 'Fealy', 'mfealy1e@nationalgeographic.com', 'Bigender', '2009-01-25', 'Sweden');
insert into users (id, first_name, last_name, email, gender, dob, country) values (52, 'Sissy', 'Ekell', 'sekell1f@pinterest.com', 'Female', '2021-08-06', 'Czech Republic');
insert into users (id, first_name, last_name, email, gender, dob, country) values (53, 'Silvio', 'Songust', 'ssongust1g@ow.ly', 'Male', '1993-08-25', 'Venezuela');
insert into users (id, first_name, last_name, email, gender, dob, country) values (54, 'Catlin', null, 'ctoor1h@java.com', 'Female', '2023-07-08', 'Puerto Rico');
insert into users (id, first_name, last_name, email, gender, dob, country) values (55, 'Brucie', null, null, 'Male', '1991-07-12', 'United States');
insert into users (id, first_name, last_name, email, gender, dob, country) values (56, 'Paulie', null, 'pcressy1j@nydailynews.com', 'Female', '1999-09-23', 'Slovenia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (57, 'Bernard', 'Wrinch', null, 'Male', '2006-06-09', 'Ireland');
insert into users (id, first_name, last_name, email, gender, dob, country) values (58, 'Hollis', 'Youd', null, 'Male', '2012-06-25', 'United States');
insert into users (id, first_name, last_name, email, gender, dob, country) values (59, 'Datha', null, 'dpencott1m@blogspot.com', 'Female', '1997-08-23', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (60, 'Nelson', 'Headey', 'nheadey1n@miibeian.gov.cn', 'Male', '2018-01-09', 'France');
insert into users (id, first_name, last_name, email, gender, dob, country) values (61, 'Godfree', null, 'ghousbey1o@behance.net', 'Genderqueer', '2016-06-05', 'Peru');
insert into users (id, first_name, last_name, email, gender, dob, country) values (62, 'Beryl', null, 'bleyman1p@furl.net', 'Female', '2001-12-31', 'United States');
insert into users (id, first_name, last_name, email, gender, dob, country) values (63, 'Beauregard', 'Son', 'bson1q@gravatar.com', 'Male', '2003-10-01', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (64, 'Caitrin', 'Gaskell', null, 'Female', '1996-03-29', 'Serbia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (65, 'Bendick', 'Moggle', null, 'Male', '2000-06-06', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (66, 'Burlie', null, 'bsnaddin1t@parallels.com', 'Male', '2001-10-21', 'Saudi Arabia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (67, 'Valry', 'Kemston', null, 'Female', '1998-12-01', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (68, 'Katina', null, null, 'Female', '2022-12-25', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (69, 'Terrill', null, 'twhordley1w@reference.com', 'Male', '2003-06-18', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (70, 'Kelby', 'Kennifick', 'kkennifick1x@purevolume.com', 'Bigender', '1994-03-06', 'Czech Republic');
insert into users (id, first_name, last_name, email, gender, dob, country) values (71, 'Tedra', 'Gonnely', 'tgonnely1y@plala.or.jp', 'Female', '2012-01-30', 'Palestinian Territory');
insert into users (id, first_name, last_name, email, gender, dob, country) values (72, 'Florina', 'South', 'fsouth1z@scientificamerican.com', 'Female', '1993-08-22', 'Argentina');
insert into users (id, first_name, last_name, email, gender, dob, country) values (73, 'Andie', 'O''Donohue', null, 'Male', '2022-03-27', 'Haiti');
insert into users (id, first_name, last_name, email, gender, dob, country) values (74, 'Bartram', 'Danbury', 'bdanbury21@skyrock.com', 'Male', '2012-06-14', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (75, 'Joni', 'Imlach', 'jimlach22@senate.gov', 'Female', '1991-01-08', 'Portugal');
insert into users (id, first_name, last_name, email, gender, dob, country) values (76, 'Felix', null, 'fkellart23@zimbio.com', 'Male', '2003-07-21', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (77, 'Alisander', null, 'anaisbet24@alexa.com', 'Male', '2018-12-29', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (78, 'Blake', null, 'bjakobssen25@businesswire.com', 'Male', '2015-12-14', 'Russia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (79, 'Linell', null, 'lclack26@wp.com', 'Female', '2024-07-31', 'Cuba');
insert into users (id, first_name, last_name, email, gender, dob, country) values (80, 'Peter', 'Coxall', null, 'Male', '1993-06-09', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (81, 'Silas', null, 'sskeels28@baidu.com', 'Male', '2016-10-14', 'France');
insert into users (id, first_name, last_name, email, gender, dob, country) values (82, 'Tally', null, null, 'Female', '1995-08-23', 'Ukraine');
insert into users (id, first_name, last_name, email, gender, dob, country) values (83, 'Carr', 'Linfitt', 'clinfitt2a@mail.ru', 'Male', '2012-11-29', 'Japan');
insert into users (id, first_name, last_name, email, gender, dob, country) values (84, 'Bendick', 'McNab', 'bmcnab2b@google.ca', 'Male', '1999-11-26', 'France');
insert into users (id, first_name, last_name, email, gender, dob, country) values (85, 'Traver', 'Giampietro', 'tgiampietro2c@ibm.com', 'Male', '2013-06-06', 'Mauritius');
insert into users (id, first_name, last_name, email, gender, dob, country) values (86, 'Gene', 'Rollings', null, 'Male', '2020-02-12', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (87, 'Niel', 'Iozefovich', 'niozefovich2e@canalblog.com', 'Male', '2003-04-26', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (88, 'Corly', 'Roglieri', 'croglieri2f@bing.com', 'Female', '2018-09-22', 'Tanzania');
insert into users (id, first_name, last_name, email, gender, dob, country) values (89, 'Lanni', 'Pane', 'lpane2g@about.me', 'Female', '2003-06-14', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (90, 'Carlye', 'Bernardinelli', 'cbernardinelli2h@foxnews.com', 'Female', '2012-07-23', 'Russia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (91, 'Wyndham', 'Stuchbery', 'wstuchbery2i@marriott.com', 'Male', '2008-06-02', 'Germany');
insert into users (id, first_name, last_name, email, gender, dob, country) values (92, 'Cliff', 'Cecil', null, 'Male', '2009-04-03', 'Ghana');
insert into users (id, first_name, last_name, email, gender, dob, country) values (93, 'Rhody', 'Buxey', null, 'Female', '2023-05-19', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (94, 'Ernaline', null, 'ewhitehorne2l@nifty.com', 'Female', '2019-12-27', 'Uruguay');
insert into users (id, first_name, last_name, email, gender, dob, country) values (95, 'Brunhilda', 'Pinsent', 'bpinsent2m@networksolutions.com', 'Female', '2024-07-04', 'Russia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (96, 'Sula', 'Hayton', 'shayton2n@ucla.edu', 'Female', '2024-02-09', 'Greece');
insert into users (id, first_name, last_name, email, gender, dob, country) values (97, 'Abbey', null, 'agearing2o@twitpic.com', 'Female', '2009-05-03', 'Israel');
insert into users (id, first_name, last_name, email, gender, dob, country) values (98, 'Broderic', 'Benech', null, 'Male', '2006-06-19', 'Afghanistan');
insert into users (id, first_name, last_name, email, gender, dob, country) values (99, 'Cameron', 'Geke', null, 'Male', '2012-06-28', 'Japan');
insert into users (id, first_name, last_name, email, gender, dob, country) values (100, 'Borden', 'Landrick', 'blandrick2r@google.pl', 'Male', '2016-04-11', 'Argentina');
insert into users (id, first_name, last_name, email, gender, dob, country) values (101, 'Sayer', 'Shurman', 'sshurman2s@google.co.uk', 'Male', '1996-05-25', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (102, 'Lorette', 'Yearron', 'lyearron2t@yelp.com', 'Genderfluid', '1995-07-09', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (103, 'Philomena', 'Gartsyde', 'pgartsyde2u@vkontakte.ru', 'Female', '2012-07-20', 'Costa Rica');
insert into users (id, first_name, last_name, email, gender, dob, country) values (104, 'Crysta', 'Eglinton', 'ceglinton2v@ca.gov', 'Female', '2012-01-21', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (105, 'Louie', 'Shivlin', 'lshivlin2w@cbc.ca', 'Male', '2024-11-22', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (106, 'Georgianne', 'Ciciotti', null, 'Female', '2001-06-30', 'Russia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (107, 'Shirley', null, 'sruzek2y@deliciousdays.com', 'Female', '2009-03-29', 'Bangladesh');
insert into users (id, first_name, last_name, email, gender, dob, country) values (108, 'Crawford', null, 'cbritton2z@over-blog.com', 'Male', '2021-06-07', 'Portugal');
insert into users (id, first_name, last_name, email, gender, dob, country) values (109, 'Pen', 'Sperwell', 'psperwell30@virginia.edu', 'Female', '1997-02-22', 'Bangladesh');
insert into users (id, first_name, last_name, email, gender, dob, country) values (110, 'Frederic', null, 'fdevil31@wiley.com', 'Male', '2009-04-24', 'Kazakhstan');
insert into users (id, first_name, last_name, email, gender, dob, country) values (111, 'Maura', 'Hallor', 'mhallor32@shop-pro.jp', 'Female', '1996-01-05', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (112, 'Estel', null, 'echase33@google.es', 'Female', '1999-05-12', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (113, 'Jude', 'Campanelle', 'jcampanelle34@buzzfeed.com', 'Male', '2022-10-05', 'Angola');
insert into users (id, first_name, last_name, email, gender, dob, country) values (114, 'Jens', null, 'jmcqueen35@whitehouse.gov', 'Male', '2022-09-15', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (115, 'Elsworth', 'Kochs', null, 'Male', '2007-11-25', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (116, 'Gibby', 'Tubbles', 'gtubbles37@ucla.edu', 'Male', '1998-02-27', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (117, 'Burton', 'Shillam', 'bshillam38@vistaprint.com', 'Male', '2022-02-13', 'United States');
insert into users (id, first_name, last_name, email, gender, dob, country) values (118, 'Damian', 'Durman', null, 'Male', '2007-08-05', 'Poland');
insert into users (id, first_name, last_name, email, gender, dob, country) values (119, 'Farlay', null, 'fjoint3a@de.vu', 'Agender', '2000-09-10', 'Guatemala');
insert into users (id, first_name, last_name, email, gender, dob, country) values (120, 'Basilio', null, 'bburnip3b@indiegogo.com', 'Polygender', '2026-03-03', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (121, 'Ruttger', 'Getcliffe', null, 'Non-binary', '2000-12-30', 'Russia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (122, 'Marnia', 'Waine', 'mwaine3d@redcross.org', 'Female', '2014-05-01', 'Russia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (123, 'Quillan', 'Birkhead', null, 'Male', '2019-01-12', 'Ivory Coast');
insert into users (id, first_name, last_name, email, gender, dob, country) values (124, 'Euphemia', 'Peile', null, 'Female', '2001-02-28', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (125, 'Rebeka', 'Gandley', 'rgandley3g@jimdo.com', 'Female', '2009-06-06', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (126, 'Carlynne', null, null, 'Female', '1993-07-09', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (127, 'Kurt', 'Harrigan', 'kharrigan3i@bing.com', 'Male', '2025-03-01', 'Russia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (128, 'Faulkner', null, null, 'Male', '2006-12-08', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (129, 'Carrol', null, 'cviegas3k@illinois.edu', 'Polygender', '2013-05-26', 'Peru');
insert into users (id, first_name, last_name, email, gender, dob, country) values (130, 'Ive', null, 'irainton3l@narod.ru', 'Male', '1995-01-09', 'United Kingdom');
insert into users (id, first_name, last_name, email, gender, dob, country) values (131, 'Ermin', 'Eite', 'eeite3m@posterous.com', 'Male', '1992-09-07', 'Austria');
insert into users (id, first_name, last_name, email, gender, dob, country) values (132, 'Malcolm', null, 'mdoust3n@vimeo.com', 'Male', '1998-08-09', 'Serbia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (133, 'Martica', 'Rehn', 'mrehn3o@intel.com', 'Female', '2004-11-27', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (134, 'Fulton', null, null, 'Male', '2002-07-12', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (135, 'Reagan', 'Kuhnel', null, 'Male', '2005-08-07', 'Argentina');
insert into users (id, first_name, last_name, email, gender, dob, country) values (136, 'Rolland', 'Hydes', 'rhydes3r@shinystat.com', 'Non-binary', '2020-02-05', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (137, 'Drusie', 'Doggrell', 'ddoggrell3s@gnu.org', 'Female', '2005-07-03', 'Syria');
insert into users (id, first_name, last_name, email, gender, dob, country) values (138, 'Keelia', 'Lishmund', 'klishmund3t@g.co', 'Female', '1998-06-26', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (139, 'Logan', 'Cawthery', 'lcawthery3u@so-net.ne.jp', 'Male', '1998-10-07', 'North Korea');
insert into users (id, first_name, last_name, email, gender, dob, country) values (140, 'Gabie', 'Haster', null, 'Male', '2015-06-04', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (141, 'Dulcea', 'Rippen', 'drippen3w@multiply.com', 'Female', '2023-09-27', 'Thailand');
insert into users (id, first_name, last_name, email, gender, dob, country) values (142, 'Sammy', null, null, 'Male', '2025-01-14', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (143, 'Dylan', 'Mendoza', 'dmendoza3y@umich.edu', 'Male', '1992-08-20', 'Libya');
insert into users (id, first_name, last_name, email, gender, dob, country) values (144, 'Shannan', 'Wigley', 'swigley3z@51.la', 'Male', '2001-03-01', 'Armenia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (145, 'Drusi', 'Reinert', null, 'Female', '2007-02-22', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (146, 'Horace', 'MacQueen', 'hmacqueen41@goodreads.com', 'Male', '2008-02-16', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (147, 'Moritz', 'Fairholme', 'mfairholme42@github.com', 'Polygender', '2015-07-26', 'Ukraine');
insert into users (id, first_name, last_name, email, gender, dob, country) values (148, 'Hillary', 'Gillease', 'hgillease43@tripadvisor.com', 'Male', '1996-10-09', 'Niger');
insert into users (id, first_name, last_name, email, gender, dob, country) values (149, 'Mommy', 'Henkmann', null, 'Female', '1996-07-11', 'Sweden');
insert into users (id, first_name, last_name, email, gender, dob, country) values (150, 'Rozanna', 'Scatcher', 'rscatcher45@bravesites.com', 'Female', '2010-10-13', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (151, 'Tully', 'Kee', 'tkee46@edublogs.org', 'Male', '1992-11-29', 'Cuba');
insert into users (id, first_name, last_name, email, gender, dob, country) values (152, 'Kahaleel', 'Cluett', 'kcluett47@mapy.cz', 'Male', '1998-08-16', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (153, 'Tab', 'Whiteside', 'twhiteside48@devhub.com', 'Male', '2016-03-28', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (154, 'Kacy', 'Loyd', 'kloyd49@globo.com', 'Female', '2000-03-12', 'Portugal');
insert into users (id, first_name, last_name, email, gender, dob, country) values (155, 'Dorelia', 'Abelwhite', 'dabelwhite4a@sfgate.com', 'Female', '2001-02-10', 'Albania');
insert into users (id, first_name, last_name, email, gender, dob, country) values (156, 'Chelsy', null, 'clindwall4b@shinystat.com', 'Female', '1996-09-11', 'France');
insert into users (id, first_name, last_name, email, gender, dob, country) values (157, 'Logan', 'Pundy', 'lpundy4c@macromedia.com', 'Male', '2018-09-06', 'Russia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (158, 'Milissent', 'Dyet', 'mdyet4d@mlb.com', 'Genderfluid', '1996-11-07', 'Germany');
insert into users (id, first_name, last_name, email, gender, dob, country) values (159, 'Adriano', 'Lunny', 'alunny4e@oakley.com', 'Male', '1991-04-01', 'Canada');
insert into users (id, first_name, last_name, email, gender, dob, country) values (160, 'Kippie', 'Gronowe', 'kgronowe4f@simplemachines.org', 'Female', '2015-07-16', 'Honduras');
insert into users (id, first_name, last_name, email, gender, dob, country) values (161, 'Ari', 'Helsdon', 'ahelsdon4g@bravesites.com', 'Male', '2009-08-27', 'Vietnam');
insert into users (id, first_name, last_name, email, gender, dob, country) values (162, 'Ashien', 'Portlock', null, 'Female', '2002-11-18', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (163, 'Meg', null, null, 'Female', '1991-08-03', 'Niger');
insert into users (id, first_name, last_name, email, gender, dob, country) values (164, 'Jephthah', 'Hardcastle', 'jhardcastle4j@mozilla.org', 'Male', '1998-12-22', 'Democratic Republic of the Congo');
insert into users (id, first_name, last_name, email, gender, dob, country) values (165, 'Faustina', null, 'fpeyzer4k@berkeley.edu', 'Female', '2012-12-03', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (166, 'Lexine', 'Castelluzzi', 'lcastelluzzi4l@posterous.com', 'Female', '2016-07-13', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (167, 'Tiebout', 'Balmadier', 'tbalmadier4m@discovery.com', 'Male', '2025-08-04', 'United States');
insert into users (id, first_name, last_name, email, gender, dob, country) values (168, 'Kirstyn', 'Hannabus', null, 'Female', '1999-08-18', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (169, 'Peadar', 'Serginson', 'pserginson4o@amazonaws.com', 'Male', '1994-04-11', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (170, 'Marni', null, 'mgatcliff4p@woothemes.com', 'Female', '1995-05-28', 'Cayman Islands');
insert into users (id, first_name, last_name, email, gender, dob, country) values (171, 'Hoyt', null, 'hsavine4q@people.com.cn', 'Male', '1992-03-19', 'Latvia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (172, 'Roman', 'Saill', null, 'Genderqueer', '1996-10-04', 'Bosnia and Herzegovina');
insert into users (id, first_name, last_name, email, gender, dob, country) values (173, 'Hillary', 'Edridge', 'hedridge4s@cbslocal.com', 'Female', '2021-08-23', 'Germany');
insert into users (id, first_name, last_name, email, gender, dob, country) values (174, 'Franky', null, 'fdocker4t@mozilla.com', 'Female', '2009-07-04', 'Peru');
insert into users (id, first_name, last_name, email, gender, dob, country) values (175, 'Doll', 'Elliff', null, 'Female', '1992-11-09', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (176, 'Riccardo', 'Masi', 'rmasi4v@cargocollective.com', 'Male', '1993-07-03', 'Japan');
insert into users (id, first_name, last_name, email, gender, dob, country) values (177, 'Bethena', null, 'bnorssister4w@php.net', 'Female', '2013-08-24', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (178, 'Shellysheldon', null, null, 'Male', '2006-12-17', 'United States');
insert into users (id, first_name, last_name, email, gender, dob, country) values (179, 'Noami', 'Ech', 'nech4y@feedburner.com', 'Bigender', '2013-12-16', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (180, 'Auguste', 'Orridge', 'aorridge4z@rambler.ru', 'Female', '2025-11-17', 'Guyana');
insert into users (id, first_name, last_name, email, gender, dob, country) values (181, 'Veronike', null, 'vscolli50@admin.ch', 'Female', '2012-03-17', 'Morocco');
insert into users (id, first_name, last_name, email, gender, dob, country) values (182, 'Tessa', null, 'tbaumler51@creativecommons.org', 'Female', '2002-04-23', 'Poland');
insert into users (id, first_name, last_name, email, gender, dob, country) values (183, 'Dacy', 'Olivier', null, 'Polygender', '1992-07-11', 'Panama');
insert into users (id, first_name, last_name, email, gender, dob, country) values (184, 'Janeczka', 'McEnteggart', null, 'Female', '2002-09-30', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (185, 'Dorri', null, null, 'Female', '2017-01-06', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (186, 'Shelley', 'Overpool', 'soverpool55@histats.com', 'Female', '2012-04-03', 'South Africa');
insert into users (id, first_name, last_name, email, gender, dob, country) values (187, 'Rickie', 'Bover', 'rbover56@smh.com.au', 'Bigender', '1991-12-29', 'Saint Lucia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (188, 'Ashlee', 'Peirazzi', 'apeirazzi57@twitpic.com', 'Female', '2016-05-21', 'Bulgaria');
insert into users (id, first_name, last_name, email, gender, dob, country) values (189, 'Jared', 'Vaskov', 'jvaskov58@scientificamerican.com', 'Male', '2013-04-03', 'Brazil');
insert into users (id, first_name, last_name, email, gender, dob, country) values (190, 'Leann', 'Fowgies', 'lfowgies59@imageshack.us', 'Female', '2014-12-24', 'Afghanistan');
insert into users (id, first_name, last_name, email, gender, dob, country) values (191, 'Germaine', 'Joanaud', null, 'Male', '2006-06-26', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (192, 'Claresta', 'Dunseith', null, 'Female', '2008-05-20', 'Netherlands');
insert into users (id, first_name, last_name, email, gender, dob, country) values (193, 'Cosette', null, null, 'Female', '1996-02-03', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (194, 'Bendix', 'Hanmore', null, 'Male', '2002-04-15', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (195, 'Bartel', 'Foux', 'bfoux5e@people.com.cn', 'Male', '1996-09-29', 'Poland');
insert into users (id, first_name, last_name, email, gender, dob, country) values (196, 'Stefanie', 'Brend', 'sbrend5f@ebay.com', 'Female', '2023-11-07', 'Russia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (197, 'Price', 'Le Surf', 'plesurf5g@unicef.org', 'Non-binary', '2022-06-11', 'France');
insert into users (id, first_name, last_name, email, gender, dob, country) values (198, 'Angelica', null, 'amccole5h@blinklist.com', 'Genderqueer', '2024-06-07', 'Armenia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (199, 'Ewan', 'Godart', 'egodart5i@pagesperso-orange.fr', 'Male', '2012-01-10', 'Portugal');
insert into users (id, first_name, last_name, email, gender, dob, country) values (200, 'Alyssa', null, 'aoaker5j@marriott.com', 'Female', '1992-10-19', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (201, 'Van', 'Jancar', null, 'Male', '2017-02-21', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (202, 'Gussi', 'Loxston', 'gloxston5l@washingtonpost.com', 'Female', '1994-12-04', 'Mauritius');
insert into users (id, first_name, last_name, email, gender, dob, country) values (203, 'Celisse', 'Tite', 'ctite5m@blogspot.com', 'Female', '2002-05-18', 'Argentina');
insert into users (id, first_name, last_name, email, gender, dob, country) values (204, 'Kira', null, null, 'Female', '2017-03-13', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (205, 'Ranique', 'Gromley', 'rgromley5o@redcross.org', 'Female', '1996-10-30', 'Libya');
insert into users (id, first_name, last_name, email, gender, dob, country) values (206, 'Pammi', 'Mushart', null, 'Female', '2019-04-20', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (207, 'Abbott', 'Sturdgess', 'asturdgess5q@live.com', 'Male', '2022-04-24', 'Syria');
insert into users (id, first_name, last_name, email, gender, dob, country) values (208, 'Tobi', 'Hickinbottom', 'thickinbottom5r@msu.edu', 'Female', '2004-01-13', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (209, 'Nadine', 'Flanigan', 'nflanigan5s@edublogs.org', 'Female', '2016-10-30', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (210, 'Ignazio', 'Seeney', null, 'Male', '2014-01-15', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (211, 'Gay', null, null, 'Male', '2001-09-06', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (212, 'Holly', 'Gimblet', 'hgimblet5v@rediff.com', 'Male', '2002-09-13', 'Czech Republic');
insert into users (id, first_name, last_name, email, gender, dob, country) values (213, 'Arther', 'Arndtsen', null, 'Male', '2025-03-01', 'Croatia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (214, 'Dionne', 'Eastment', 'deastment5x@ifeng.com', 'Female', '2000-02-18', 'Vietnam');
insert into users (id, first_name, last_name, email, gender, dob, country) values (215, 'Susan', 'Rannells', 'srannells5y@people.com.cn', 'Female', '2010-03-07', 'United States');
insert into users (id, first_name, last_name, email, gender, dob, country) values (216, 'Jocelin', null, null, 'Female', '1993-07-13', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (217, 'Junette', 'McKevitt', 'jmckevitt60@apache.org', 'Female', '2001-09-20', 'Portugal');
insert into users (id, first_name, last_name, email, gender, dob, country) values (218, 'Tanny', 'Lesaunier', 'tlesaunier61@webeden.co.uk', 'Male', '2009-12-06', 'Peru');
insert into users (id, first_name, last_name, email, gender, dob, country) values (219, 'Frank', null, null, 'Female', '1998-07-27', 'Argentina');
insert into users (id, first_name, last_name, email, gender, dob, country) values (220, 'Burg', 'Alldritt', null, 'Genderqueer', '2015-02-22', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (221, 'Rafael', 'Bicker', 'rbicker64@mtv.com', 'Male', '2007-10-24', 'Brazil');
insert into users (id, first_name, last_name, email, gender, dob, country) values (222, 'Dani', 'Gandley', 'dgandley65@prlog.org', 'Female', '2001-11-11', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (223, 'Jobie', 'Benedtti', 'jbenedtti66@nps.gov', 'Female', '2019-04-24', 'Bosnia and Herzegovina');
insert into users (id, first_name, last_name, email, gender, dob, country) values (224, 'Quinlan', 'Marconi', null, 'Male', '1991-03-23', 'Ukraine');
insert into users (id, first_name, last_name, email, gender, dob, country) values (225, 'Fey', 'Nanninini', 'fnanninini68@tumblr.com', 'Female', '1999-11-01', 'Czech Republic');
insert into users (id, first_name, last_name, email, gender, dob, country) values (226, 'Dosi', 'Benallack', 'dbenallack69@mit.edu', 'Genderqueer', '1998-11-22', 'Canada');
insert into users (id, first_name, last_name, email, gender, dob, country) values (227, 'Blaine', 'Mustard', 'bmustard6a@vk.com', 'Male', '2003-10-24', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (228, 'Nicholle', 'Stuffins', 'nstuffins6b@paginegialle.it', 'Female', '2024-08-20', 'Mexico');
insert into users (id, first_name, last_name, email, gender, dob, country) values (229, 'Frederica', 'Monteaux', 'fmonteaux6c@cnet.com', 'Female', '2025-01-08', 'France');
insert into users (id, first_name, last_name, email, gender, dob, country) values (230, 'Zorana', null, 'ztampling6d@cloudflare.com', 'Genderqueer', '2002-01-13', 'Portugal');
insert into users (id, first_name, last_name, email, gender, dob, country) values (231, 'Chas', 'Santori', null, 'Male', '2007-11-07', 'France');
insert into users (id, first_name, last_name, email, gender, dob, country) values (232, 'Rutger', 'Willetts', null, 'Male', '2001-12-15', 'Vietnam');
insert into users (id, first_name, last_name, email, gender, dob, country) values (233, 'Alexandro', 'Millbank', null, 'Non-binary', '2022-08-29', 'Honduras');
insert into users (id, first_name, last_name, email, gender, dob, country) values (234, 'Onofredo', 'Rutherforth', null, 'Male', '2012-11-11', 'Bhutan');
insert into users (id, first_name, last_name, email, gender, dob, country) values (235, 'Gabrielle', null, 'graffels6i@youtube.com', 'Female', '1999-05-10', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (236, 'Wald', 'McCullum', 'wmccullum6j@technorati.com', 'Male', '2004-10-13', 'Bahamas');
insert into users (id, first_name, last_name, email, gender, dob, country) values (237, 'Rosabella', 'Gravey', null, 'Female', '2019-05-07', 'Nigeria');
insert into users (id, first_name, last_name, email, gender, dob, country) values (238, 'Julia', 'Kither', 'jkither6l@lulu.com', 'Female', '1992-08-19', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (239, 'Cathe', 'Horche', null, 'Female', '2008-11-09', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (240, 'Jennica', 'Whitewood', 'jwhitewood6n@google.nl', 'Female', '2016-02-13', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (241, 'Jon', 'Spitaro', 'jspitaro6o@slideshare.net', 'Male', '2005-04-29', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (242, 'Virginie', 'Oulner', 'voulner6p@surveymonkey.com', 'Female', '2022-05-14', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (243, 'Emmie', 'Tort', 'etort6q@cloudflare.com', 'Bigender', '1990-11-11', 'China');
insert into users (id, first_name, last_name, email, gender, dob, country) values (244, 'Connie', 'Seven', 'cseven6r@nymag.com', 'Male', '2004-12-30', 'United States');
insert into users (id, first_name, last_name, email, gender, dob, country) values (245, 'Natala', 'MacGiany', null, 'Female', '2018-11-25', 'Spain');
insert into users (id, first_name, last_name, email, gender, dob, country) values (246, 'Bunnie', 'Challen', 'bchallen6t@ebay.co.uk', 'Female', '2008-12-05', 'Kazakhstan');
insert into users (id, first_name, last_name, email, gender, dob, country) values (247, 'Salvatore', 'Dearle-Palser', null, 'Male', '2023-02-19', 'Russia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (248, 'Montgomery', null, null, 'Male', '1994-11-19', 'Indonesia');
insert into users (id, first_name, last_name, email, gender, dob, country) values (249, 'Lucius', 'Price', null, 'Male', '1997-01-20', 'Philippines');
insert into users (id, first_name, last_name, email, gender, dob, country) values (250, 'Amy', 'Aitchison', null, 'Female', '1999-06-09', 'Sweden');



select * from users;

select * from users where last_name is not null order by first_name , country;
-- this gives inconsistent result due to sorting by multiple columns at once.